language: csharp
#solution: CafeApp.sln
script:
  - sh ./build.sh BuildApp
#  - xbuild /p:Configuration=Release CafeApp.sln
before_install:
  - sudo apt-get install nunit-console
after_script:
  - nunit-console ./CafeApp.Core/bin/Release/CafeApp.Core.dll
