language: csharp
solution: CafeApp.sln
install:
  - nuget restore CafeApp.sln
  - nuget install NUnit.Console -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CafeApp.sln
  - mono ./testrunner/NUnit.Console.3.6.0/tools/nunit-console.exe ./CafeApp.Core/bin/Release/CafeApp.Core.dll